Inputs

In [1]:
# =========================================
# For accessing directories
# =========================================
root_dir = "/local/data/artemis/workspace/vbennington/LDEO_HPD/2021models"
data_output_dir = f"{root_dir}/data"


Modules

In [3]:
# standard imports
import os
import datetime
from pathlib import Path
from collections import defaultdict
import scipy
import random
import numpy as np
import xarray as xr
import pandas as pd
import joblib
import pickle

# machine learning libraries
from sklearn.model_selection import train_test_split

# Python file with supporting functions
import pre_HPD

Predefined Values

In [5]:
# Loading references

In [4]:
# =========================================
# Setting the date range to unify the date type
# =========================================
# Define date range
date_range_start = '1982-01-01T00:00:00.000000000'
#date_range_start = '1990-01-01T00:00:00.000000000'
date_range_end = '2020-12-31T00:00:00.000000000'

# create date vector
dates = pd.date_range(start=date_range_start, 
                      end=date_range_end,freq='MS') + np.timedelta64(14, 'D')

Loop to load in data, clean it, and save it

In [5]:

print(datetime.datetime.now())

df = pre_HPD.create_inputs(dates,12)
#df = pre_SOCAT.create_pco2_inputs(dates,12)
df.head()
# Save the pandas data frame to my workspace
pre_HPD.save_clean_data(df, data_output_dir)

print(datetime.datetime.now())

2022-03-01 18:32:54.757180
468
<xarray.DataArray 'time' ()>
array('2020-12-15T00:00:00.000000000', dtype='datetime64[ns]')
Coordinates:
    time     datetime64[ns] 2020-12-15
<xarray.DataArray 'time' (time: 468)>
array(['1982-01-15T00:00:00.000000000', '1982-02-15T00:00:00.000000000',
       '1982-03-15T00:00:00.000000000', ..., '2020-10-15T00:00:00.000000000',
       '2020-11-15T00:00:00.000000000', '2020-12-15T00:00:00.000000000'],
      dtype='datetime64[ns]')
Coordinates:
  * time     (time) datetime64[ns] 1982-01-15 1982-02-15 ... 2020-12-15
<xarray.Dataset>
Dimensions:                (time: 468, xlon: 360, ylat: 180)
Coordinates:
  * time                   (time) datetime64[ns] 1982-01-15 ... 2020-12-15
  * xlon                   (xlon) float64 -179.5 -178.5 -177.5 ... 178.5 179.5
  * ylat                   (ylat) float64 -89.5 -88.5 -87.5 ... 87.5 88.5 89.5
Data variables:
    SSS                    (time, ylat, xlon) float64 ...
    sst                    (time, ylat, xlon) float64 ...
    chl                    (time, ylat, xlon) float64 ...
    pCO2                   (time, ylat, xlon) float64 ...
    XCO2                   (time, ylat, xlon) float64 ...
    socat_mask             (time, ylat, xlon) float64 ...
    mld                    (time, ylat, xlon) float64 0.0 0.0 0.0 ... 0.0 0.0
    cesm_sfco2_1x1_A       (time, ylat, xlon) float64 ...
    fesom2_sfco2_1x1_A     (time, ylat, xlon) float64 ...
    mpi_sfco2_1x1_A        (time, ylat, xlon) float64 ...
    cnrm_sfco2_1x1_A       (time, ylat, xlon) float64 ...
    ipsl_sfco2_1x1_A       (time, ylat, xlon) float64 ...
    planktom_sfco2_1x1_A   (time, ylat, xlon) float64 ...
    noresm_sfco2_1x1_A     (time, ylat, xlon) float64 ...
    princeton_sfco2_1x1_A  (time, ylat, xlon) float64 ...
2022-03-01 18:33:41.847082

In [7]:
# Look at the data to make sure it looks okay:
df = pd.read_pickle(f'{data_output_dir}/data_clean_2D_mon_1x1_198201-202012.pkl')

In [9]:
df.tail()

                             SSS   sst  chl  pCO2        XCO2  socat_mask  \
time       xlon  ylat
2020-12-15 179.5 85.5  31.680887 -1.79  NaN   NaN  419.006388         NaN
                 86.5  31.724632 -1.79  NaN   NaN  419.004079         NaN
                 87.5  31.649817 -1.79  NaN   NaN  419.001771         NaN
                 88.5  31.661079 -1.79  NaN   NaN  418.999463         NaN
                 89.5  31.754524 -1.79  NaN   NaN  418.997154         NaN

                             mld  cesm_sfco2_1x1_A  fesom2_sfco2_1x1_A  \
time       xlon  ylat
2020-12-15 179.5 85.5  74.964204        385.598667          283.037109
                 86.5  74.175315        386.120408          277.089600
                 87.5  71.900835        386.357330          272.581818
                 88.5   0.000000        386.701442          268.717682
                 89.5   0.000000        387.368222          267.311676

                       mpi_sfco2_1x1_A  ...  chl_log  chl_anom  sss_anom  \
time       xlon  ylat                   ...
2020-12-15 179.5 85.5       366.973877  ...      NaN       NaN  0.178074
                 86.5       366.156189  ...      NaN       NaN  0.253362
                 87.5       353.915161  ...      NaN       NaN  0.294222
                 88.5       325.212097  ...      NaN       NaN  0.324067
                 89.5       316.272400  ...      NaN       NaN  0.323254

                       sst_anom        T0        T1         A         B  \
time       xlon  ylat
2020-12-15 179.5 85.5       0.0  0.966848 -0.255353  0.996917  0.000685
                 86.5       0.0  0.966848 -0.255353  0.998135  0.000533
                 87.5       0.0  0.966848 -0.255353  0.999048  0.000381
                 88.5       0.0  0.966848 -0.255353  0.999657  0.000228
                 89.5       0.0  0.966848 -0.255353  0.999962  0.000076

                              C  net_mask
time       xlon  ylat
2020-12-15 179.5 85.5  0.078456       NaN
                 86.5  0.061046       NaN
                 87.5  0.043618       NaN
                 88.5  0.026176       NaN
                 89.5  0.008726       NaN

[5 rows x 26 columns]